name: my_sampad
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  api_service:
    git:
      url: https://github.com/hamidjalili59/api_service.git
      ref: main
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  database_service:
    git:
      url: https://github.com/hamidjalili59/database_service.git
  device_info_plus: ^9.0.2
  dio: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.11
  flutter_screenutil: ^5.5.4
  flutter_svg: ^2.0.5
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  ndialog: ^4.2.0
  persian_datetimepickers: ^1.0.3+2
  pinput: ^2.2.31
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  rename: ^2.0.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.5.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/students/
    - assets/icons/parents/
    - assets/icons/head_master/
    - assets/icons/teachers/
    - assets/icons/course/
    - assets/fonts/
    - assets/fonts/ordibehesht/
    - assets/svgs/
    - assets/svgs/icons/


  fonts:
    - family: Ordibehesht
      fonts:
        - asset: assets/fonts/ordibehesht/Ordibehesht.TTF
